### ISSUE TITLE
'Found 0 spots' 

### ISSUE THREAD

**Issue by simonecnascimento** [trackmate-sc/TrackMate-Cellpose#6]
It seems to always give me  ‘Found 0 spots’ and Java error:
java.lang.IllegalArgumentException: Stack argument out of range: 1
	at ij.ImageStack.getProcessor(ImageStack.java:310)
	at net.imglib2.img.imageplus.ShortImagePlus.<init>(ShortImagePlus.java:98)
	at net.imglib2.img.ImagePlusAdapter.wrapShort(ImagePlusAdapter.java:172)
	at net.imglib2.img.ImagePlusAdapter.wrapLocal(ImagePlusAdapter.java:102)
	at net.imglib2.img.ImagePlusAdapter.wrap(ImagePlusAdapter.java:74)
	at net.imglib2.img.ImagePlusAdapter.wrapImgPlus(ImagePlusAdapter.java:91)
	at fiji.plugin.trackmate.util.TMUtils.rawWraps(TMUtils.java:142)
	at fiji.plugin.trackmate.TrackMate.execDetection(TrackMate.java:356)
	at fiji.plugin.trackmate.detection.DetectionUtils$1.run(DetectionUtils.java:134)

I am using 16-bit image stack, red channel. Cells ranging from 50-100px. 

Thank you!

**Comment by simonecnascimento** [comment]
Hi @tinevez,

This is a 2D tif stack (1999frames), 16-bit, recorded on the red channel. Cells are shown in white, elongated, not stained for nucleus.
![test_cellpose_params](https://github.com/trackmate-sc/TrackMate-Cellpose/assets/54689806/12999630-aa56-4b5c-86c2-669f1d427fe7)
![test_cellpose](https://github.com/trackmate-sc/TrackMate-Cellpose/assets/54689806/5cdee1d4-efe1-4a5f-b79c-a50b31691cee)

Thank you!

**Comment by simonecnascimento** [comment]
Hi @tinevez,

This is a 2D tif stack (1999frames), 16-bit, recorded on the red channel. Cells are shown in white, elongated, not stained for nucleus.


![test_cellpose](https://github.com/trackmate-sc/TrackMate-Cellpose/assets/54689806/f2c47576-7633-41ff-9c3d-53b249b2d1aa)
![test_cellpose_params](https://github.com/trackmate-sc/TrackMate-Cellpose/assets/54689806/f891c569-52de-48e0-8914-4181b1db4587)


Thank you!

**Comment by tinevez** [comment]
Any change I could get the data itself?

**Comment by tinevez** [comment]
I have decent results with the following settings:
![Screenshot 2023-06-13 at 09 09 16](https://github.com/trackmate-sc/TrackMate-Cellpose/assets/3583203/c2631d26-de62-4055-87eb-94178cf235e5)

![Screenshot 2023-06-13 at 09 15 05](https://github.com/trackmate-sc/TrackMate-Cellpose/assets/3583203/e2ce3c0f-b747-4444-87cf-7f778cf85baa)

It's far from perfect, but I think this is close to the best you can get given the image complexity and with the builtin models.

The reason you get 0 spots might be linked to 2 things:

- We realized you need to run cellpose at least once outside of TrackMate, *before running TrackMate*, so that the builtin models can be downloaded from the internet.

- The size parameter is crucial. One of the gotcha is that in TrackMate they are in physical units (µm), while in normal cellpose they are in pixels. In your case I just used 30 pixels.
-

**Comment by tinevez** [comment]
Any news @simonecnascimento ?

**Comment by simonecnascimento** [comment]
Hi @tinevez 

Sorry for the delay in replying, I actually had to change my machine as it was incredibly slow and it was always freezing when I opened cellpose GUI.

Now I managed to train the cyto model, but the issue now is with cellpose integration with Trackmate:

[ERROR] Could not instantiate fiji.plugin.trackmate.cellpose.CellposeDetectorFactory
org.scijava.InstantiableException: Class not found: fiji.plugin.trackmate.cellpose.CellposeDetectorFactory
	at org.scijava.plugin.PluginInfo.loadClass(PluginInfo.java:285)
	at org.scijava.plugin.PluginInfo.createInstance(PluginInfo.java:297)
	at fiji.plugin.trackmate.providers.AbstractProvider.registerModules(AbstractProvider.java:68)
	at fiji.plugin.trackmate.providers.AbstractProvider.<init>(AbstractProvider.java:25)
	at fiji.plugin.trackmate.providers.DetectorProvider.<init>(DetectorProvider.java:11)
	at fiji.plugin.trackmate.gui.TrackMateGUIController.createProviders(TrackMateGUIController.java:496)
	at fiji.plugin.trackmate.gui.TrackMateGUIController.<init>(TrackMateGUIController.java:257)
	at fiji.plugin.trackmate.TrackMatePlugIn_.run(TrackMatePlugIn_.java:67)
	at ij.IJ.runUserPlugIn(IJ.java:229)
	at ij.IJ.runPlugIn(IJ.java:193)
	at ij.Executer.runCommand(Executer.java:137)
	at ij.Executer.run(Executer.java:66)
	at java.lang.Thread.run(Thread.java:662)

I added 'http://sites.imagej.net/TrackMate-Cellpose/' on the updates, but not sure why I am having this issue now. Other detectors seem to work fine.

Any idea why?

Thank you again!

**Comment by tinevez** [comment]
> [ERROR] Could not instantiate fiji.plugin.trackmate.cellpose.CellposeDetectorFactory
> org.scijava.InstantiableException: Class not found: fiji.plugin.trackmate.cellpose.CellposeDetectorFactory
> at org.scijava.plugin.PluginInfo.loadClass(PluginInfo.java:285)

Ok this is very weird. It basically states that it cannot find the class that corresponds to the cellpose extension you installed. But at the same time, since it appeared in the menu, you should have been able to get it. 

Of course I cannot reproduce it on my side.

I suspect something odd with your Fiji installation. Could you try to download a fresh Fiji at https://fiji.sc, and do not install anything except the TrackMate-Cellpose extension?

**Comment by simonecnascimento** [comment]
It worked! Thanks a lot.
I used Cyto 2.0 and gave me quite some spots, but not all. 
I will try to train a model with my own images to see if it can detect more spots. 

Thank you very much again!
